apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: backend
  namespace: smart-home
spec:
  serviceName: backend-headless
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-flask-container
          image: nadavnv/smart-home-backend-flask:V1.1.0
          resources:
            limits:
              cpu: 300m
              memory: 200Mi
            requests:
              cpu: 200m
              memory: 100Mi
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_PASS
              valueFrom:
                secretKeyRef:
                  key: password
                  name: redis-password
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: mongo-credentials
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mongo-credentials
            - name: BROKER_HOST
              valueFrom:
                configMapKeyRef:
                  name: mqtt-broker-cm
                  key: BROKER_HOST
            - name: BROKER_PORT
              valueFrom:
                configMapKeyRef:
                  name: mqtt-broker-cm
                  key: BROKER_PORT
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: jwt-secret-key
                  name: jwt-secret-key
          livenessProbe:
            httpGet:
              path: /healthy
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
        - name: backend-nginx-container
          image: nadavnv/smart-home-backend-nginx:V1.1.0
          resources:
            limits:
              cpu: 300m
              memory: 200Mi
            requests:
              cpu: 200m
              memory: 100Mi
          ports:
            - containerPort: 5200
          livenessProbe:
            httpGet:
              path: /healthy
              port: 5200
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 5200
            initialDelaySeconds: 10
            periodSeconds: 5
          env:
            - name: FLASK_BACKEND_HOST
              value: localhost
---
# Backend service
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: smart-home
spec:
  # ClusterIP by default
  selector:
    app: backend
  ports:
    - port: 5200
      targetPort: 5200
---
apiVersion: v1
kind: Service
metadata:
  name: backend-headless
  namespace: smart-home
spec:
  clusterIP: None
  selector:
    app: backend
  ports:
    - port: 5200
      targetPort: 5200
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: smart-home
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: backend
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
