apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smart-home
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: smart-home
  source:
    repoURL: https://github.com/NadavNV/SmartHomeConfig.git
    path: kubernetes/
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
