apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-home-simulator-deploy
  namespace: smart-home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-home-simulator
  template:
    metadata:
      name: smart-home-simulator-pod
      labels:
        app: smart-home-simulator
    spec:
      containers:
        - name: smart-home-simulator-container
          image: yardenziv/smarthome_simulator:latest
          resources:
            limits:
              cpu: 300m
              memory: 200Mi
            requests:
              cpu: 200m
              memory: 100Mi
          env:
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: smart-home-cm
                  key: API_URL
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - cat status | grep healthy

            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - cat status | grep ready
            initialDelaySeconds: 10
            periodSeconds: 5
