apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: smart-home
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'flask-backend'
        static_configs:
          - targets: ['smart-home-backend-svc.smart-home.svc.cluster.local:5200']
